FROM openjdk:8u212

RUN dd if=/dev/urandom of=/large.tmp.file.1 bs=1048576 count=50
RUN dd if=/dev/urandom of=/large.tmp.file.2 bs=1048576 count=50
RUN dd if=/dev/urandom of=/large.tmp.file.3 bs=1048576 count=50
RUN dd if=/dev/urandom of=/large.tmp.file.4 bs=1048576 count=50
RUN dd if=/dev/urandom of=/large.tmp.file.5 bs=1048576 count=50
RUN dd if=/dev/urandom of=/large.tmp.file.6 bs=1048576 count=50
RUN dd if=/dev/urandom of=/large.tmp.file.7 bs=1048576 count=50
RUN dd if=/dev/urandom of=/large.tmp.file.8 bs=1048576 count=50
RUN dd if=/dev/urandom of=/large.tmp.file.9 bs=1048576 count=50
RUN dd if=/dev/urandom of=/large.tmp.file.10 bs=1048576 count=50
RUN dd if=/dev/urandom of=/large.tmp.file.11 bs=1048576 count=50
RUN dd if=/dev/urandom of=/large.tmp.file.12 bs=1048576 count=50
RUN dd if=/dev/urandom of=/large.tmp.file.13 bs=1048576 count=50
